// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceLigueHockey.Data;

#nullable disable

namespace ServiceLigueHockeyV2.Migrations
{
    [DbContext(typeof(ServiceLigueHockeyContext))]
    [Migration("20250628013247_AjoutDivisionConference")]
    partial class AjoutDivisionConference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.AnneeStatsBd", b =>
                {
                    b.Property<short>("AnneeStats")
                        .HasColumnType("smallint");

                    b.Property<string>("DescnCourte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DescnLongue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AnneeStats");

                    b.ToTable("AnneeStats", (string)null);

                    b.HasData(
                        new
                        {
                            AnneeStats = (short)2024,
                            DescnCourte = "2024/2025",
                            DescnLongue = "Représente la saison 2024/2025"
                        },
                        new
                        {
                            AnneeStats = (short)2023,
                            DescnCourte = "2023/2024",
                            DescnLongue = "Représente la saison 2023/2024"
                        },
                        new
                        {
                            AnneeStats = (short)2022,
                            DescnCourte = "2022/2023",
                            DescnLongue = "Représente la saison 2022/2023"
                        },
                        new
                        {
                            AnneeStats = (short)2021,
                            DescnCourte = "2021/2022",
                            DescnLongue = "Représente la saison 2021/2022"
                        },
                        new
                        {
                            AnneeStats = (short)2020,
                            DescnCourte = "2020/2021",
                            DescnLongue = "Représente la saison 2020/2021"
                        },
                        new
                        {
                            AnneeStats = (short)2019,
                            DescnCourte = "2019/2020",
                            DescnLongue = "Représente la saison 2019/2020"
                        },
                        new
                        {
                            AnneeStats = (short)2018,
                            DescnCourte = "2018/2019",
                            DescnLongue = "Représente la saison 2018/2019"
                        },
                        new
                        {
                            AnneeStats = (short)2017,
                            DescnCourte = "2017/2018",
                            DescnLongue = "Représente la saison 2017/2018"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.ConferenceBd", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AnneeDebut")
                        .HasColumnType("int");

                    b.Property<int?>("AnneeFin")
                        .HasColumnType("int");

                    b.Property<int?>("EstDevenueConference")
                        .HasColumnType("int");

                    b.Property<string>("NomConference")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("NomConference", "AnneeDebut")
                        .IsUnique();

                    b.ToTable("Conference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeDebut = 1994,
                            NomConference = "Est"
                        },
                        new
                        {
                            Id = 2,
                            AnneeDebut = 1994,
                            NomConference = "Ouest"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.DivisionBd", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AnneeDebut")
                        .HasColumnType("int");

                    b.Property<int?>("AnneeFin")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("NomDivision")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("NomDivision", "AnneeDebut")
                        .IsUnique();

                    b.ToTable("Division", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeDebut = 1994,
                            ConferenceId = 1,
                            NomDivision = "Atlantique"
                        },
                        new
                        {
                            Id = 2,
                            AnneeDebut = 1994,
                            ConferenceId = 1,
                            NomDivision = "Métropolitaine"
                        },
                        new
                        {
                            Id = 3,
                            AnneeDebut = 1994,
                            ConferenceId = 2,
                            NomDivision = "Centrale"
                        },
                        new
                        {
                            Id = 4,
                            AnneeDebut = 1994,
                            ConferenceId = 2,
                            NomDivision = "Pacifique"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.EquipeBd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeDebut")
                        .HasColumnType("int");

                    b.Property<int?>("AnneeFin")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int?>("EstDevenueEquipe")
                        .HasColumnType("int");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("NomEquipe", "Ville")
                        .IsUnique();

                    b.ToTable("Equipe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeDebut = 1989,
                            DivisionId = 1,
                            NomEquipe = "Canadiensssss",
                            Ville = "Mourial"
                        },
                        new
                        {
                            Id = 2,
                            AnneeDebut = 1984,
                            DivisionId = 1,
                            NomEquipe = "Bruns",
                            Ville = "Albany"
                        },
                        new
                        {
                            Id = 3,
                            AnneeDebut = 1976,
                            DivisionId = 1,
                            NomEquipe = "Harfangs",
                            Ville = "Hartford"
                        },
                        new
                        {
                            Id = 4,
                            AnneeDebut = 1999,
                            DivisionId = 1,
                            NomEquipe = "Boulettes",
                            Ville = "Victoriaville"
                        },
                        new
                        {
                            Id = 5,
                            AnneeDebut = 2001,
                            DivisionId = 1,
                            NomEquipe = "Rocher",
                            Ville = "Percé"
                        },
                        new
                        {
                            Id = 6,
                            AnneeDebut = 1986,
                            DivisionId = 1,
                            NomEquipe = "Pierre",
                            Ville = "Rochester"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.EquipeJoueurBd", b =>
                {
                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebutAvecEquipe")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateFinAvecEquipe")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("NoDossard")
                        .HasColumnType("smallint");

                    b.HasKey("EquipeId", "JoueurId", "DateDebutAvecEquipe");

                    b.HasIndex("JoueurId");

                    b.ToTable("EquipeJoueur", (string)null);

                    b.HasData(
                        new
                        {
                            EquipeId = 1,
                            JoueurId = 1,
                            DateDebutAvecEquipe = new DateTime(2008, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)23
                        },
                        new
                        {
                            EquipeId = 1,
                            JoueurId = 2,
                            DateDebutAvecEquipe = new DateTime(2016, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)24
                        },
                        new
                        {
                            EquipeId = 1,
                            JoueurId = 3,
                            DateDebutAvecEquipe = new DateTime(2017, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)25
                        },
                        new
                        {
                            EquipeId = 1,
                            JoueurId = 4,
                            DateDebutAvecEquipe = new DateTime(2013, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)26
                        },
                        new
                        {
                            EquipeId = 2,
                            JoueurId = 5,
                            DateDebutAvecEquipe = new DateTime(2014, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)27
                        },
                        new
                        {
                            EquipeId = 2,
                            JoueurId = 6,
                            DateDebutAvecEquipe = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)28
                        },
                        new
                        {
                            EquipeId = 2,
                            JoueurId = 7,
                            DateDebutAvecEquipe = new DateTime(2018, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)29
                        },
                        new
                        {
                            EquipeId = 2,
                            JoueurId = 8,
                            DateDebutAvecEquipe = new DateTime(2010, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)30
                        },
                        new
                        {
                            EquipeId = 3,
                            JoueurId = 9,
                            DateDebutAvecEquipe = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)31
                        },
                        new
                        {
                            EquipeId = 3,
                            JoueurId = 10,
                            DateDebutAvecEquipe = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)32
                        },
                        new
                        {
                            EquipeId = 3,
                            JoueurId = 11,
                            DateDebutAvecEquipe = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)33
                        },
                        new
                        {
                            EquipeId = 4,
                            JoueurId = 12,
                            DateDebutAvecEquipe = new DateTime(2011, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)34
                        },
                        new
                        {
                            EquipeId = 4,
                            JoueurId = 13,
                            DateDebutAvecEquipe = new DateTime(2012, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoDossard = (short)35
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.JoueurBd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaysOrigine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VilleNaissance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Joueur", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1988, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Tremblay",
                            PaysOrigine = "Canada",
                            Prenom = "Jack",
                            VilleNaissance = "Lévis"
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1996, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Lajeunesse",
                            PaysOrigine = "Canada",
                            Prenom = "Simon",
                            VilleNaissance = "St-Stanislas"
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1995, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Grandpré",
                            PaysOrigine = "Canada",
                            Prenom = "Mathieu",
                            VilleNaissance = "Val d'or"
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1991, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Callahan",
                            PaysOrigine = "Canada",
                            Prenom = "Ryan",
                            VilleNaissance = "London"
                        },
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1992, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "McCain",
                            PaysOrigine = "États-Unis",
                            Prenom = "Drew",
                            VilleNaissance = "Albany"
                        },
                        new
                        {
                            Id = 6,
                            DateNaissance = new DateTime(2000, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Harris",
                            PaysOrigine = "États-Unis",
                            Prenom = "John",
                            VilleNaissance = "Chico"
                        },
                        new
                        {
                            Id = 7,
                            DateNaissance = new DateTime(1996, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Rodgers",
                            PaysOrigine = "Canada",
                            Prenom = "Phil",
                            VilleNaissance = "Calgary"
                        },
                        new
                        {
                            Id = 8,
                            DateNaissance = new DateTime(1992, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Rodriguez",
                            PaysOrigine = "Canada",
                            Prenom = "Ted",
                            VilleNaissance = "Regina"
                        },
                        new
                        {
                            Id = 9,
                            DateNaissance = new DateTime(1998, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Lemieux",
                            PaysOrigine = "Canada",
                            Prenom = "Patrice",
                            VilleNaissance = "Chibougamau"
                        },
                        new
                        {
                            Id = 10,
                            DateNaissance = new DateTime(1997, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Béliveau",
                            PaysOrigine = "Canada",
                            Prenom = "Maurice",
                            VilleNaissance = "Beauceville"
                        },
                        new
                        {
                            Id = 11,
                            DateNaissance = new DateTime(1997, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Cruz",
                            PaysOrigine = "États-Unis",
                            Prenom = "Andrew",
                            VilleNaissance = "Dallas"
                        },
                        new
                        {
                            Id = 12,
                            DateNaissance = new DateTime(1991, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Trout",
                            PaysOrigine = "États-Unis",
                            Prenom = "Chris",
                            VilleNaissance = "Eau Claire"
                        },
                        new
                        {
                            Id = 13,
                            DateNaissance = new DateTime(1992, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Datzyuk",
                            PaysOrigine = "États-Unis",
                            Prenom = "Sergei",
                            VilleNaissance = "Eau Claire"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.ParametresBd", b =>
                {
                    b.Property<string>("nom")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("valeur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("nom", "dateDebut");

                    b.ToTable("Parametres", (string)null);

                    b.HasData(
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "82"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2021, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "56"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2020, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "71"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2019, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "82"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2012, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2013, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "48"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2005, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2012, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "82"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(2004, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2005, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "0"
                        },
                        new
                        {
                            nom = "nombrePartiesJouees",
                            dateDebut = new DateTime(1995, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateFin = new DateTime(2004, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "82"
                        },
                        new
                        {
                            nom = "AjoutSteve",
                            dateDebut = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valeur = "ma valeur"
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PartieBd", b =>
                {
                    b.Property<int>("IdPartie")
                        .HasColumnType("int");

                    b.Property<string>("AFiniEnProlongation")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("AFiniEnTirDeBarrage")
                        .HasColumnType("varchar(1)");

                    b.Property<short>("AnneeStats")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DatePartieJouee")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstUnePartieDeSerie")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EstUnePartiePresaison")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EstUnePartieSaisonReguliere")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("IdEquipeHote")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipeVisiteuse")
                        .HasColumnType("int");

                    b.Property<short?>("NbreButsComptesParHote")
                        .HasColumnType("smallint");

                    b.Property<short?>("NbreButsComptesParVisiteur")
                        .HasColumnType("smallint");

                    b.Property<string>("SommairePartie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPartie");

                    b.HasIndex("AnneeStats");

                    b.HasIndex("IdEquipeVisiteuse");

                    b.HasIndex("IdEquipeHote", "IdEquipeVisiteuse", "DatePartieJouee")
                        .IsUnique();

                    b.ToTable("Partie", (string)null);

                    b.HasData(
                        new
                        {
                            IdPartie = 1,
                            AnneeStats = (short)2024,
                            DatePartieJouee = new DateTime(2024, 10, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EstUnePartieDeSerie = "N",
                            EstUnePartiePresaison = "N",
                            EstUnePartieSaisonReguliere = "O",
                            IdEquipeHote = 1,
                            IdEquipeVisiteuse = 2,
                            SommairePartie = ""
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.Penalite_TypePenaliteBd", b =>
                {
                    b.Property<int>("IdPenalite")
                        .HasColumnType("int");

                    b.Property<int>("IdJoueurPenalise")
                        .HasColumnType("int");

                    b.Property<short>("IdTypePenalite")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("MomentDelaPenalite")
                        .HasColumnType("time(6)");

                    b.HasKey("IdPenalite");

                    b.HasIndex("IdTypePenalite");

                    b.HasIndex("MomentDelaPenalite", "IdJoueurPenalise");

                    b.ToTable("Penalite_TypePenalite", (string)null);
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PenalitesBd", b =>
                {
                    b.Property<TimeSpan>("MomentDelaPenalite")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdPartie")
                        .HasColumnType("int");

                    b.Property<int>("IdJoueurPenalise")
                        .HasColumnType("int");

                    b.HasKey("MomentDelaPenalite", "IdPartie");

                    b.HasIndex("IdJoueurPenalise");

                    b.HasIndex("IdPartie");

                    b.ToTable("Penalites", (string)null);
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PointeursBd", b =>
                {
                    b.Property<int>("IdPartie")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("MomentDuButMarque")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdJoueurButMarque")
                        .HasColumnType("int");

                    b.Property<int?>("IdJoueurPremiereAssistance")
                        .HasColumnType("int");

                    b.Property<int?>("IdJoueurSecondeAssistance")
                        .HasColumnType("int");

                    b.HasKey("IdPartie", "MomentDuButMarque");

                    b.ToTable("FeuillePointage", (string)null);
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.StatsEquipeBd", b =>
                {
                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<short>("AnneeStats")
                        .HasColumnType("smallint");

                    b.Property<int>("NbButsContre")
                        .HasColumnType("int");

                    b.Property<int>("NbButsPour")
                        .HasColumnType("int");

                    b.Property<short?>("NbDefProlo")
                        .HasColumnType("smallint");

                    b.Property<short>("NbDefaites")
                        .HasColumnType("smallint");

                    b.Property<short>("NbPartiesJouees")
                        .HasColumnType("smallint");

                    b.Property<short>("NbVictoires")
                        .HasColumnType("smallint");

                    b.HasKey("EquipeId", "AnneeStats");

                    b.ToTable("StatsEquipe", (string)null);

                    b.HasData(
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2023,
                            NbButsContre = 267,
                            NbButsPour = 380,
                            NbDefProlo = (short)12,
                            NbDefaites = (short)20,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)50
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2023,
                            NbButsContre = 287,
                            NbButsPour = 315,
                            NbDefProlo = (short)11,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)45
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2023,
                            NbButsContre = 307,
                            NbButsPour = 300,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)30,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)44
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2023,
                            NbButsContre = 337,
                            NbButsPour = 280,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)40,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)34
                        },
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2022,
                            NbButsContre = 267,
                            NbButsPour = 380,
                            NbDefProlo = (short)12,
                            NbDefaites = (short)20,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)50
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2022,
                            NbButsContre = 287,
                            NbButsPour = 315,
                            NbDefProlo = (short)11,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)45
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2022,
                            NbButsContre = 307,
                            NbButsPour = 300,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)30,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)44
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2022,
                            NbButsContre = 337,
                            NbButsPour = 280,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)40,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)34
                        },
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2021,
                            NbButsContre = 267,
                            NbButsPour = 380,
                            NbDefProlo = (short)12,
                            NbDefaites = (short)20,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)50
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2021,
                            NbButsContre = 287,
                            NbButsPour = 315,
                            NbDefProlo = (short)11,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)45
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2021,
                            NbButsContre = 307,
                            NbButsPour = 300,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)30,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)44
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2021,
                            NbButsContre = 337,
                            NbButsPour = 280,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)40,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)34
                        },
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2020,
                            NbButsContre = 267,
                            NbButsPour = 380,
                            NbDefProlo = (short)12,
                            NbDefaites = (short)20,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)50
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2020,
                            NbButsContre = 287,
                            NbButsPour = 315,
                            NbDefProlo = (short)11,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)45
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2020,
                            NbButsContre = 307,
                            NbButsPour = 300,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)30,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)44
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2020,
                            NbButsContre = 337,
                            NbButsPour = 280,
                            NbDefProlo = (short)8,
                            NbDefaites = (short)40,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)34
                        },
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2019,
                            NbButsContre = 290,
                            NbButsPour = 330,
                            NbDefProlo = (short)10,
                            NbDefaites = (short)29,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)43
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2019,
                            NbButsContre = 255,
                            NbButsPour = 345,
                            NbDefProlo = (short)13,
                            NbDefaites = (short)21,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)48
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2019,
                            NbButsContre = 295,
                            NbButsPour = 320,
                            NbDefProlo = (short)10,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)46
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2019,
                            NbButsContre = 307,
                            NbButsPour = 311,
                            NbDefProlo = (short)11,
                            NbDefaites = (short)33,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)38
                        },
                        new
                        {
                            EquipeId = 1,
                            AnneeStats = (short)2018,
                            NbButsContre = 312,
                            NbButsPour = 310,
                            NbDefProlo = (short)15,
                            NbDefaites = (short)34,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)33
                        },
                        new
                        {
                            EquipeId = 2,
                            AnneeStats = (short)2018,
                            NbButsContre = 275,
                            NbButsPour = 340,
                            NbDefProlo = (short)14,
                            NbDefaites = (short)23,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)45
                        },
                        new
                        {
                            EquipeId = 3,
                            AnneeStats = (short)2018,
                            NbButsContre = 298,
                            NbButsPour = 340,
                            NbDefProlo = (short)9,
                            NbDefaites = (short)26,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)47
                        },
                        new
                        {
                            EquipeId = 4,
                            AnneeStats = (short)2018,
                            NbButsContre = 280,
                            NbButsPour = 341,
                            NbDefProlo = (short)10,
                            NbDefaites = (short)31,
                            NbPartiesJouees = (short)82,
                            NbVictoires = (short)41
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.StatsJoueurBd", b =>
                {
                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<short>("AnneeStats")
                        .HasColumnType("smallint");

                    b.Property<int>("ButsAlloues")
                        .HasColumnType("int");

                    b.Property<short>("Defaites")
                        .HasColumnType("smallint");

                    b.Property<short>("DefaitesEnProlongation")
                        .HasColumnType("smallint");

                    b.Property<double>("MinutesJouees")
                        .HasColumnType("double");

                    b.Property<short>("NbButs")
                        .HasColumnType("smallint");

                    b.Property<short>("NbMinutesPenalites")
                        .HasColumnType("smallint");

                    b.Property<short>("NbPartiesJouees")
                        .HasColumnType("smallint");

                    b.Property<short>("NbPasses")
                        .HasColumnType("smallint");

                    b.Property<short>("NbPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("Nulles")
                        .HasColumnType("smallint");

                    b.Property<short>("PlusseMoins")
                        .HasColumnType("smallint");

                    b.Property<int>("TirsAlloues")
                        .HasColumnType("int");

                    b.Property<short>("Victoires")
                        .HasColumnType("smallint");

                    b.HasKey("JoueurId", "EquipeId", "AnneeStats");

                    b.HasIndex("EquipeId");

                    b.ToTable("StatsJoueur", (string)null);

                    b.HasData(
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2023,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)10,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)20,
                            NbPoints = (short)30,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2023,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)15,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)10,
                            NbPoints = (short)25,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2023,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)5,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)24,
                            NbPoints = (short)29,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2023,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)0,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)0,
                            NbPoints = (short)0,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        },
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2022,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)10,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)20,
                            NbPoints = (short)30,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2022,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)15,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)10,
                            NbPoints = (short)25,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2022,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)5,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)24,
                            NbPoints = (short)29,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2022,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)0,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)0,
                            NbPoints = (short)0,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        },
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2021,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)10,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)20,
                            NbPoints = (short)30,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2021,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)15,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)10,
                            NbPoints = (short)25,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2021,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)5,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)24,
                            NbPoints = (short)29,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2021,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)0,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)0,
                            NbPoints = (short)0,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        },
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2020,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)10,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)20,
                            NbPoints = (short)30,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2020,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)15,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)10,
                            NbPoints = (short)25,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2020,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)5,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)24,
                            NbPoints = (short)29,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2020,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)0,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)25,
                            NbPasses = (short)0,
                            NbPoints = (short)0,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        },
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2019,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1910,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)82,
                            NbPasses = (short)20,
                            NbPoints = (short)1930,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2019,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1915,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)82,
                            NbPasses = (short)10,
                            NbPoints = (short)1925,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2019,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1905,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)82,
                            NbPasses = (short)24,
                            NbPoints = (short)1929,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2019,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)1900,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)82,
                            NbPasses = (short)0,
                            NbPoints = (short)1900,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        },
                        new
                        {
                            JoueurId = 1,
                            EquipeId = 1,
                            AnneeStats = (short)2018,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1810,
                            NbMinutesPenalites = (short)15,
                            NbPartiesJouees = (short)65,
                            NbPasses = (short)20,
                            NbPoints = (short)1830,
                            Nulles = (short)0,
                            PlusseMoins = (short)5,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 2,
                            EquipeId = 1,
                            AnneeStats = (short)2018,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1815,
                            NbMinutesPenalites = (short)51,
                            NbPartiesJouees = (short)65,
                            NbPasses = (short)10,
                            NbPoints = (short)1825,
                            Nulles = (short)0,
                            PlusseMoins = (short)-2,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 3,
                            EquipeId = 1,
                            AnneeStats = (short)2018,
                            ButsAlloues = 0,
                            Defaites = (short)0,
                            DefaitesEnProlongation = (short)0,
                            MinutesJouees = 500.0,
                            NbButs = (short)1805,
                            NbMinutesPenalites = (short)35,
                            NbPartiesJouees = (short)65,
                            NbPasses = (short)24,
                            NbPoints = (short)1829,
                            Nulles = (short)0,
                            PlusseMoins = (short)25,
                            TirsAlloues = 0,
                            Victoires = (short)0
                        },
                        new
                        {
                            JoueurId = 4,
                            EquipeId = 1,
                            AnneeStats = (short)2018,
                            ButsAlloues = 53,
                            Defaites = (short)2,
                            DefaitesEnProlongation = (short)6,
                            MinutesJouees = 1500.0,
                            NbButs = (short)1800,
                            NbMinutesPenalites = (short)4,
                            NbPartiesJouees = (short)65,
                            NbPasses = (short)0,
                            NbPoints = (short)1800,
                            Nulles = (short)0,
                            PlusseMoins = (short)0,
                            TirsAlloues = 564,
                            Victoires = (short)9
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.TypePenalitesBd", b =>
                {
                    b.Property<short>("IdTypePenalite")
                        .HasColumnType("smallint");

                    b.Property<string>("DescriptionPenalite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NbreMinutesPenalitesPourCetteInfraction")
                        .HasColumnType("int");

                    b.HasKey("IdTypePenalite");

                    b.ToTable("TypePenalites", (string)null);

                    b.HasData(
                        new
                        {
                            IdTypePenalite = (short)1,
                            DescriptionPenalite = "Mineure",
                            NbreMinutesPenalitesPourCetteInfraction = 2
                        },
                        new
                        {
                            IdTypePenalite = (short)2,
                            DescriptionPenalite = "Majeure",
                            NbreMinutesPenalitesPourCetteInfraction = 5
                        },
                        new
                        {
                            IdTypePenalite = (short)3,
                            DescriptionPenalite = "Inconduite de partie",
                            NbreMinutesPenalitesPourCetteInfraction = 10
                        });
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.DivisionBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.ConferenceBd", "ConferenceParent")
                        .WithMany("listeDivision")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceParent");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.EquipeBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.DivisionBd", "division")
                        .WithMany("listeEquipeBd")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("division");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.EquipeJoueurBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.EquipeBd", "Equipe")
                        .WithMany("listeEquipeJoueur")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.JoueurBd", "Joueur")
                        .WithMany("listeEquipeJoueur")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PartieBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.AnneeStatsBd", "zeAnnee")
                        .WithMany("listeParties")
                        .HasForeignKey("AnneeStats")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.EquipeBd", "EquipeHote")
                        .WithMany("listeEquipeHote")
                        .HasForeignKey("IdEquipeHote")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.EquipeBd", "EquipeVisiteuse")
                        .WithMany("listeEquipeVisiteur")
                        .HasForeignKey("IdEquipeVisiteuse")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EquipeHote");

                    b.Navigation("EquipeVisiteuse");

                    b.Navigation("zeAnnee");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.Penalite_TypePenaliteBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.TypePenalitesBd", "typePenalitesParent")
                        .WithMany("listePenTypePen")
                        .HasForeignKey("IdTypePenalite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.PenalitesBd", "penaliteParent")
                        .WithMany("listePenalites")
                        .HasForeignKey("MomentDelaPenalite", "IdJoueurPenalise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("penaliteParent");

                    b.Navigation("typePenalitesParent");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PenalitesBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.JoueurBd", "joueurPenalise")
                        .WithMany("listePenalites")
                        .HasForeignKey("IdJoueurPenalise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.PartieBd", "MonCalendrier")
                        .WithMany("listePenalites")
                        .HasForeignKey("IdPartie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MonCalendrier");

                    b.Navigation("joueurPenalise");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PointeursBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.PartieBd", "MonCalendrier")
                        .WithMany("listePointeurs")
                        .HasForeignKey("IdPartie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MonCalendrier");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.StatsEquipeBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.EquipeBd", "Equipe")
                        .WithMany("listeStatsEquipe")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.StatsJoueurBd", b =>
                {
                    b.HasOne("ServiceLigueHockey.Data.Models.EquipeBd", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceLigueHockey.Data.Models.JoueurBd", "Joueur")
                        .WithMany("listeStatsJoueur")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.AnneeStatsBd", b =>
                {
                    b.Navigation("listeParties");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.ConferenceBd", b =>
                {
                    b.Navigation("listeDivision");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.DivisionBd", b =>
                {
                    b.Navigation("listeEquipeBd");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.EquipeBd", b =>
                {
                    b.Navigation("listeEquipeHote");

                    b.Navigation("listeEquipeJoueur");

                    b.Navigation("listeEquipeVisiteur");

                    b.Navigation("listeStatsEquipe");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.JoueurBd", b =>
                {
                    b.Navigation("listeEquipeJoueur");

                    b.Navigation("listePenalites");

                    b.Navigation("listeStatsJoueur");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PartieBd", b =>
                {
                    b.Navigation("listePenalites");

                    b.Navigation("listePointeurs");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.PenalitesBd", b =>
                {
                    b.Navigation("listePenalites");
                });

            modelBuilder.Entity("ServiceLigueHockey.Data.Models.TypePenalitesBd", b =>
                {
                    b.Navigation("listePenTypePen");
                });
#pragma warning restore 612, 618
        }
    }
}
